version: 0.2

phases:
  install:
    commands:
      - cd cicd # change directory
      - bash configure-named-profile.sh 
      - bash k8s-tools-install.sh

  pre_build:
    commands:
      - echo build started on `date`
      - echo "this where we are going to run bash push-to-ecr.sh"
      # - bash push-to-ecr.sh
      - echo "let's create k8s cluster called spacex-cluster" 
      - make delete_cluster
      - echo build finished on `date`

      
  # build:
  #   commands:
  #     - echo build started on `date`
  #     - bash deploy-k8s.sh
  #     - echo build finished on `date`