version: 0.2

phases:
  install:
    commands:
      - cd cicd # change directory
      - echo "First step to be built"
      - bash configure-named-profile.sh # configure named profile
      - bash k8s-tools-install.sh

  pre_build:
    commands:
      - pwd # show the current dir
      - bash push-to-ecr.sh


  # build:
  #   commands:
  #     - echo build started on `date`
  #     - bash deploy-k8s.sh
  #     - echo build finished on `date`