apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: spacex-cluster
  region: us-east-1

nodeGroups:
  - name: ng-spacex
    instanceType: t2.small
    desiredCapacity: 2
    volumeSize: 80
    ssh:
      allow: true